version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    platform: linux/x86_64
    container_name: app_db
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.conf:/etc/mysql/conf.d
    environment:
      - MYSQL_USER=posse
      - MYSQL_PASSWORD=posse
      - MYSQL_DATABASE=webapp
      - MYSQL_ROOT_PASSWORD=0821

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db